# Generated by Django 5.0.6 on 2024-05-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=20)),
                ('eidtora', models.CharField(max_length=10)),
                ('ano_publicacao', models.DateField()),
            ],
        ),
    ]
