# Generated by Django 5.0.6 on 2024-05-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=20)),
                ('Editora', models.CharField(max_length=10)),
                ('ano_publicacao', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cadastro_livro',
        ),
    ]
