# Generated by Django 5.0.6 on 2024-05-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_livro_delete_cadastro_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='Editora',
            new_name='editora',
        ),
        migrations.RenameField(
            model_name='livro',
            old_name='título',
            new_name='titulo',
        ),
    ]
